### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/Unpublish#9]
* [x] UI Matching the publish dialog #4, #7 
* [x] Unpublished in single schedule at time specified #8, #11 
* [x] Update readme to template format #10, #12 

Once these features are in, we have a version 1.0
